version: 2.1

executors:
  buildpack:
    docker:
      - image: circleci/buildpack-deps:buster
    working_directory: ~/repo

jobs:
  build-docker-image:
    executor: buildpack
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build docker image
          command: docker build -f Dockerfile -t aws-cli .
      - run:
          name: Build docker image serverless flavor
          command: docker build -f Dockerfile.serverless -t aws-cli .
      - run:
          name: Check kubectl
          command:  docker run -it aws-cli "which" "kubectl"
      - run:
          name: Check aws
          command:  docker run -it aws-cli "aws" "--version"    

  publish-latest-docker-image:
    executor: buildpack
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build docker image
          command: |
            docker build -f Dockerfile -t "aegirops/aws-cli:latest" -t "aegirops/aws-cli:${CIRCLE_TAG}" . --no-cache
      - run:
          name: Build docker image serverless flavor
          command: |
            docker build -f Dockerfile.serverless -t "aegirops/aws-cli:latest-serverless" -t "aegirops/aws-cli:${CIRCLE_TAG}-serverless" . --no-cache
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push aegirops/aws-cli:latest
            docker push aegirops/aws-cli:${CIRCLE_TAG}
            docker push aegirops/aws-cli:latest-serverless
            docker push aegirops/aws-cli:${CIRCLE_TAG}-serverless

workflows:
  build-test:
    jobs:
      - build-docker-image:
          filters:
            branches:
              only:
                - /.*/

  publish:
    jobs:  
      - publish-latest-docker-image:
          context: dockerAwsCli
          filters:
            branches:
              ignore:
                - /.*/
            tags:
              only:
                - /^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}/
